language: python

python:
  - "3.6"
cache: 
  -  pip

install:
  -  pip install -r requirements.txt
  -  pip install pytest
  -  pip install coveralls
  -  pip install coverage

script:
  - pytest 
  - coverage run -m pytest


after_success:
  - coveralls
  - coverage report -m